"""empty message

Revision ID: 15432602dde6
Revises: 7171a7da1fcf
Create Date: 2024-04-19 09:39:10.333484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15432602dde6'
down_revision = '7171a7da1fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('passenger', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_unique_constraint('character_name_key', ['name'])

    op.drop_table('vehicle')
    # ### end Alembic commands ###
